src/Entity/Depot.php
<?php

namespace App\Entity;

use App\Repository\DepotRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=DepotRepository::class)
 */
class Depot
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lien_de_travail;

    /**
     * @ORM\ManyToOne(targetEntity=Travail::class, inversedBy="depots")
     */
    private $travail;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="depots")
     */
    private $etudiant;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $note;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLienDeTravail(): ?string
    {
        return $this->lien_de_travail;
    }

    public function setLienDeTravail(?string $lien_de_travail): self
    {
        $this->lien_de_travail = $lien_de_travail;

        return $this;
    }

    public function getTravail(): ?Travail
    {
        return $this->travail;
    }

    public function setTravail(?Travail $travail): self
    {
        $this->travail = $travail;

        return $this;
    }

    public function getEtudiant(): ?User
    {
        return $this->etudiant;
    }

    public function setEtudiant(?User $etudiant): self
    {
        $this->etudiant = $etudiant;

        return $this;
    }

    public function getNote(): ?int
    {
        return $this->note;
    }

    public function setNote(?int $note): self
    {
        $this->note = $note;

        return $this;
    }
}

src/Form/DepotType.php
<?php

namespace App\Form;

use App\Entity\Depot;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class DepotType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('lien_de_travail')
            ->add('save', SubmitType::class, [
                'attr' => ['class' => 'save'],
                ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Depot::class,
        ]);
    }
}

src/Controller/DepotController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;
use App\Entity\Depot;
use App\Form\DepotType;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\User;
use App\Entity\Travail;
use App\Form\NoteType;




class DepotController extends AbstractController
{
    /**
     * @Route("/depot", name="depot")
     */
    public function index(): Response
    {
        return $this->render('depot/index.html.twig', [
            'controller_name' => 'DepotController',
        ]);
    }
    /**
     * @Route("/depot/new/{id_user}/{id_travail}", name="depot_new")
     */
    public function addDepot(Request $request, $id_user , $id_travail)
    {
        $Depot = new Depot();
        $form = $this->createForm(DepotType::class, $Depot);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $etudiant= $this->getUser();
            $Depot->setEtudiant($etudiant);
            $travail= $this->getDoctrine()->getRepository(Travail::class)->findOneBy(array('id' => $id_travail));
            $Depot->setTravail($travail);
            $Depot->setLienDeTravail($form['lien_de_travail']->getData());
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($Depot);
            $entityManager->flush();
            

            return $this->redirectToRoute('travail_index', [], Response::HTTP_SEE_OTHER);
        }
        

        return $this->renderForm('depot/addDepot.html.twig', [
            'form' => $form,

        ]);

        
        
    }

    

    /**
     * @Route("/NoterDepot/{id}", name="NoterDepot", methods={"GET", "POST"})
     */
    public function NoterDepot(Request $request, $id)
    {
        $depot= $this->getDoctrine()->getRepository(Depot::class)->findOneBy(array('id' => $id));
        $form = $this->createForm(NoteType::class, $depot);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $depot->setNote($form['note']->getData());
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($depot);
            $entityManager->flush();
            $id= $depot->getTravail()->getId();
            


            return $this->redirectToRoute('voirlistedepot', array(
                'id' => $id,
        ));
        }
        

        return $this->renderForm('depot/NoterDepot.html.twig', [
            'form' => $form,

        ]);

    }

}

templates/depot/Voir-liste-Depot.html.twig
<table class="table">
        <thead>
            <tr>
                <th>Lien travail</th>
                <th>Noter</th>
            </tr>
        </thead>
        <tbody>
        {% for depot in travail.depots %}
            <tr>
                <td>{{ depot.id }}</td>
                <td>{{ depot.lienDeTravail }}</td>
                 <td>
                  
                    <a href="{{ path('NoterDepot', {'id': depot.id}) }}">Noter</a>


                </td>

            </tr>
        {% endfor %}
        </tbody>
    </table>

templates/depot/addDepot.html.twig
{{ form (form) }}

templates/depot/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello DepotController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/MSI/First-try/src/Controller/DepotController.php'|file_link(0) }}">src/Controller/DepotController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/MSI/First-try/templates/depot/index.html.twig'|file_link(0) }}">templates/depot/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/depot/noterDepot.html.twig
{{ form (form) }}